In [1]:
# -*- coding: utf-8 -*-
"""
Customized on Fri May 1 15:50:25 2022

@author: Thaer
"""

# ============ Select optimizers =================
# PSO_UDA, GWO_UDA, HHO_UDA, CSA_UDA, ACSA_UDA
#optimizer=["ACSA_UDA","MCSA2_UDA"]
#optimizer=["BAT_UDA","CSA_UDA","DE_UDA","GA2_UDA","GSA_UDA","GWO_UDA","HHO_UDA","JAYA_UDA","PSO_UDA","SSA_UDA","WOA_UDA", "SCA_UDA"]

# done part 1
#optimizer=["JAYA_UDA","PSO_UDA","SSA_UDA","WOA_UDA","SCA_UDA"]

# done part 2 GWO HHO SCA

#optimizer = ["SCA_UDA"]
#optimizer=["CSA_UDA","MRCSA_UDA","TCSA_UDA", "ECSA_UDA"]
#optimizer = ["ECSA_UDA"]
optimizer=["CSA_UDA","MRCSA_UDA","TCSA_UDA","ECSA_UDA"]
#=================================================


# ============ Select tested benchmark function" =================
# "F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12","F13","F14","F15","F16","F17","F18","F19"
#objectivefunc=["F1","F2", "F3","F4","F5", "F6","F7","F8", "F9","F10"] 

objectivefunc = []
Functions_No = 23
for i in range (0,Functions_No):
    func = "F"+str(i+1)
    objectivefunc.append(func)
'''objectivefunc = []
Functions_No = 30
for i in range (0,Functions_No):
    func = "F"+str(i+1)+"CEC2014"
    objectivefunc.append(func)'''
#=================================================

# ============ Select number of repetitions for each experiment=================
# To obtain meaningful statistical results, usually 30 independent runs are executed for each algorithm.
NumOfRuns = 30


# Select general parameters for all optimizers (population size, number of iterations) ....
params = {"PopulationSize": 30, "Iterations": 500}

# Choose whether to Export the results in different formats
export_flags = {
    "Export_avg": True,
    "Export_details": True,
    "Export_diversity": True,
    "Export_convergence": False,
    "Export_boxplot": False,
}


<h2>Run Framework</h2>

In [2]:
# Run Framework
from optimizer import run

run(optimizer, objectivefunc, NumOfRuns, params, export_flags)

CSA , F1  Run  0 F1  completed
CSA , F1  Run  1 F1  completed
CSA , F1  Run  2 F1  completed
CSA , F1  Run  3 F1  completed
CSA , F1  Run  4 F1  completed
CSA , F1  Run  5 F1  completed
CSA , F1  Run  6 F1  completed
CSA , F1  Run  7 F1  completed
CSA , F1  Run  8 F1  completed
CSA , F1  Run  9 F1  completed
CSA , F1  Run  10 F1  completed
CSA , F1  Run  11 F1  completed
CSA , F1  Run  12 F1  completed
CSA , F1  Run  13 F1  completed
CSA , F1  Run  14 F1  completed
CSA , F1  Run  15 F1  completed
CSA , F1  Run  16 F1  completed
CSA , F1  Run  17 F1  completed
CSA , F1  Run  18 F1  completed
CSA , F1  Run  19 F1  completed
CSA , F1  Run  20 F1  completed
CSA , F1  Run  21 F1  completed
CSA , F1  Run  22 F1  completed
CSA , F1  Run  23 F1  completed
CSA , F1  Run  24 F1  completed
CSA , F1  Run  25 F1  completed
CSA , F1  Run  26 F1  completed
CSA , F1  Run  27 F1  completed
CSA , F1  Run  28 F1  completed
CSA , F1  Run  29 F1  completed
CSA , F2  Run  0 F2  completed
CSA , F2  Run  1 F2

CSA , F9  Run  19 F9  completed
CSA , F9  Run  20 F9  completed
CSA , F9  Run  21 F9  completed
CSA , F9  Run  22 F9  completed
CSA , F9  Run  23 F9  completed
CSA , F9  Run  24 F9  completed
CSA , F9  Run  25 F9  completed
CSA , F9  Run  26 F9  completed
CSA , F9  Run  27 F9  completed
CSA , F9  Run  28 F9  completed
CSA , F9  Run  29 F9  completed
CSA , F10  Run  0 F10  completed
CSA , F10  Run  1 F10  completed
CSA , F10  Run  2 F10  completed
CSA , F10  Run  3 F10  completed
CSA , F10  Run  4 F10  completed
CSA , F10  Run  5 F10  completed
CSA , F10  Run  6 F10  completed
CSA , F10  Run  7 F10  completed
CSA , F10  Run  8 F10  completed
CSA , F10  Run  9 F10  completed
CSA , F10  Run  10 F10  completed
CSA , F10  Run  11 F10  completed
CSA , F10  Run  12 F10  completed
CSA , F10  Run  13 F10  completed
CSA , F10  Run  14 F10  completed
CSA , F10  Run  15 F10  completed
CSA , F10  Run  16 F10  completed
CSA , F10  Run  17 F10  completed
CSA , F10  Run  18 F10  completed
CSA , F10  R

CSA , F17  Run  23 F17  completed
CSA , F17  Run  24 F17  completed
CSA , F17  Run  25 F17  completed
CSA , F17  Run  26 F17  completed
CSA , F17  Run  27 F17  completed
CSA , F17  Run  28 F17  completed
CSA , F17  Run  29 F17  completed
CSA , F18  Run  0 F18  completed
CSA , F18  Run  1 F18  completed
CSA , F18  Run  2 F18  completed
CSA , F18  Run  3 F18  completed
CSA , F18  Run  4 F18  completed
CSA , F18  Run  5 F18  completed
CSA , F18  Run  6 F18  completed
CSA , F18  Run  7 F18  completed
CSA , F18  Run  8 F18  completed
CSA , F18  Run  9 F18  completed
CSA , F18  Run  10 F18  completed
CSA , F18  Run  11 F18  completed
CSA , F18  Run  12 F18  completed
CSA , F18  Run  13 F18  completed
CSA , F18  Run  14 F18  completed
CSA , F18  Run  15 F18  completed
CSA , F18  Run  16 F18  completed
CSA , F18  Run  17 F18  completed
CSA , F18  Run  18 F18  completed
CSA , F18  Run  19 F18  completed
CSA , F18  Run  20 F18  completed
CSA , F18  Run  21 F18  completed
CSA , F18  Run  22 F18  

MRCSA , F2  Run  27 F2  completed
MRCSA , F2  Run  28 F2  completed
MRCSA , F2  Run  29 F2  completed
MRCSA , F3  Run  0 F3  completed
MRCSA , F3  Run  1 F3  completed
MRCSA , F3  Run  2 F3  completed
MRCSA , F3  Run  3 F3  completed
MRCSA , F3  Run  4 F3  completed
MRCSA , F3  Run  5 F3  completed
MRCSA , F3  Run  6 F3  completed
MRCSA , F3  Run  7 F3  completed
MRCSA , F3  Run  8 F3  completed
MRCSA , F3  Run  9 F3  completed
MRCSA , F3  Run  10 F3  completed
MRCSA , F3  Run  11 F3  completed
MRCSA , F3  Run  12 F3  completed
MRCSA , F3  Run  13 F3  completed
MRCSA , F3  Run  14 F3  completed
MRCSA , F3  Run  15 F3  completed
MRCSA , F3  Run  16 F3  completed
MRCSA , F3  Run  17 F3  completed
MRCSA , F3  Run  18 F3  completed
MRCSA , F3  Run  19 F3  completed
MRCSA , F3  Run  20 F3  completed
MRCSA , F3  Run  21 F3  completed
MRCSA , F3  Run  22 F3  completed
MRCSA , F3  Run  23 F3  completed
MRCSA , F3  Run  24 F3  completed
MRCSA , F3  Run  25 F3  completed
MRCSA , F3  Run  26 F3  

MRCSA , F10  Run  29 F10  completed
MRCSA , F11  Run  0 F11  completed
MRCSA , F11  Run  1 F11  completed
MRCSA , F11  Run  2 F11  completed
MRCSA , F11  Run  3 F11  completed
MRCSA , F11  Run  4 F11  completed
MRCSA , F11  Run  5 F11  completed
MRCSA , F11  Run  6 F11  completed
MRCSA , F11  Run  7 F11  completed
MRCSA , F11  Run  8 F11  completed
MRCSA , F11  Run  9 F11  completed
MRCSA , F11  Run  10 F11  completed
MRCSA , F11  Run  11 F11  completed
MRCSA , F11  Run  12 F11  completed
MRCSA , F11  Run  13 F11  completed
MRCSA , F11  Run  14 F11  completed
MRCSA , F11  Run  15 F11  completed
MRCSA , F11  Run  16 F11  completed
MRCSA , F11  Run  17 F11  completed
MRCSA , F11  Run  18 F11  completed
MRCSA , F11  Run  19 F11  completed
MRCSA , F11  Run  20 F11  completed
MRCSA , F11  Run  21 F11  completed
MRCSA , F11  Run  22 F11  completed
MRCSA , F11  Run  23 F11  completed
MRCSA , F11  Run  24 F11  completed
MRCSA , F11  Run  25 F11  completed
MRCSA , F11  Run  26 F11  completed
MR

MRCSA , F18  Run  19 F18  completed
MRCSA , F18  Run  20 F18  completed
MRCSA , F18  Run  21 F18  completed
MRCSA , F18  Run  22 F18  completed
MRCSA , F18  Run  23 F18  completed
MRCSA , F18  Run  24 F18  completed
MRCSA , F18  Run  25 F18  completed
MRCSA , F18  Run  26 F18  completed
MRCSA , F18  Run  27 F18  completed
MRCSA , F18  Run  28 F18  completed
MRCSA , F18  Run  29 F18  completed
MRCSA , F19  Run  0 F19  completed
MRCSA , F19  Run  1 F19  completed
MRCSA , F19  Run  2 F19  completed
MRCSA , F19  Run  3 F19  completed
MRCSA , F19  Run  4 F19  completed
MRCSA , F19  Run  5 F19  completed
MRCSA , F19  Run  6 F19  completed
MRCSA , F19  Run  7 F19  completed
MRCSA , F19  Run  8 F19  completed
MRCSA , F19  Run  9 F19  completed
MRCSA , F19  Run  10 F19  completed
MRCSA , F19  Run  11 F19  completed
MRCSA , F19  Run  12 F19  completed
MRCSA , F19  Run  13 F19  completed
MRCSA , F19  Run  14 F19  completed
MRCSA , F19  Run  15 F19  completed
MRCSA , F19  Run  16 F19  completed
MR

TCSA , F3  Run  16 F3  completed
TCSA , F3  Run  17 F3  completed
TCSA , F3  Run  18 F3  completed
TCSA , F3  Run  19 F3  completed
TCSA , F3  Run  20 F3  completed
TCSA , F3  Run  21 F3  completed
TCSA , F3  Run  22 F3  completed
TCSA , F3  Run  23 F3  completed
TCSA , F3  Run  24 F3  completed
TCSA , F3  Run  25 F3  completed
TCSA , F3  Run  26 F3  completed
TCSA , F3  Run  27 F3  completed
TCSA , F3  Run  28 F3  completed
TCSA , F3  Run  29 F3  completed
TCSA , F4  Run  0 F4  completed
TCSA , F4  Run  1 F4  completed
TCSA , F4  Run  2 F4  completed
TCSA , F4  Run  3 F4  completed
TCSA , F4  Run  4 F4  completed
TCSA , F4  Run  5 F4  completed
TCSA , F4  Run  6 F4  completed
TCSA , F4  Run  7 F4  completed
TCSA , F4  Run  8 F4  completed
TCSA , F4  Run  9 F4  completed
TCSA , F4  Run  10 F4  completed
TCSA , F4  Run  11 F4  completed
TCSA , F4  Run  12 F4  completed
TCSA , F4  Run  13 F4  completed
TCSA , F4  Run  14 F4  completed
TCSA , F4  Run  15 F4  completed
TCSA , F4  Run  16 F

TCSA , F11  Run  24 F11  completed
TCSA , F11  Run  25 F11  completed
TCSA , F11  Run  26 F11  completed
TCSA , F11  Run  27 F11  completed
TCSA , F11  Run  28 F11  completed
TCSA , F11  Run  29 F11  completed
TCSA , F12  Run  0 F12  completed
TCSA , F12  Run  1 F12  completed
TCSA , F12  Run  2 F12  completed
TCSA , F12  Run  3 F12  completed
TCSA , F12  Run  4 F12  completed
TCSA , F12  Run  5 F12  completed
TCSA , F12  Run  6 F12  completed
TCSA , F12  Run  7 F12  completed
TCSA , F12  Run  8 F12  completed
TCSA , F12  Run  9 F12  completed
TCSA , F12  Run  10 F12  completed
TCSA , F12  Run  11 F12  completed
TCSA , F12  Run  12 F12  completed
TCSA , F12  Run  13 F12  completed
TCSA , F12  Run  14 F12  completed
TCSA , F12  Run  15 F12  completed
TCSA , F12  Run  16 F12  completed
TCSA , F12  Run  17 F12  completed
TCSA , F12  Run  18 F12  completed
TCSA , F12  Run  19 F12  completed
TCSA , F12  Run  20 F12  completed
TCSA , F12  Run  21 F12  completed
TCSA , F12  Run  22 F12  compl

TCSA , F19  Run  21 F19  completed
TCSA , F19  Run  22 F19  completed
TCSA , F19  Run  23 F19  completed
TCSA , F19  Run  24 F19  completed
TCSA , F19  Run  25 F19  completed
TCSA , F19  Run  26 F19  completed
TCSA , F19  Run  27 F19  completed
TCSA , F19  Run  28 F19  completed
TCSA , F19  Run  29 F19  completed
TCSA , F20  Run  0 F20  completed
TCSA , F20  Run  1 F20  completed
TCSA , F20  Run  2 F20  completed
TCSA , F20  Run  3 F20  completed
TCSA , F20  Run  4 F20  completed
TCSA , F20  Run  5 F20  completed
TCSA , F20  Run  6 F20  completed
TCSA , F20  Run  7 F20  completed
TCSA , F20  Run  8 F20  completed
TCSA , F20  Run  9 F20  completed
TCSA , F20  Run  10 F20  completed
TCSA , F20  Run  11 F20  completed
TCSA , F20  Run  12 F20  completed
TCSA , F20  Run  13 F20  completed
TCSA , F20  Run  14 F20  completed
TCSA , F20  Run  15 F20  completed
TCSA , F20  Run  16 F20  completed
TCSA , F20  Run  17 F20  completed
TCSA , F20  Run  18 F20  completed
TCSA , F20  Run  19 F20  compl

ECSA , F4  Run  24 F4  completed
ECSA , F4  Run  25 F4  completed
ECSA , F4  Run  26 F4  completed
ECSA , F4  Run  27 F4  completed
ECSA , F4  Run  28 F4  completed
ECSA , F4  Run  29 F4  completed
ECSA , F5  Run  0 F5  completed
ECSA , F5  Run  1 F5  completed
ECSA , F5  Run  2 F5  completed
ECSA , F5  Run  3 F5  completed
ECSA , F5  Run  4 F5  completed
ECSA , F5  Run  5 F5  completed
ECSA , F5  Run  6 F5  completed
ECSA , F5  Run  7 F5  completed
ECSA , F5  Run  8 F5  completed
ECSA , F5  Run  9 F5  completed
ECSA , F5  Run  10 F5  completed
ECSA , F5  Run  11 F5  completed
ECSA , F5  Run  12 F5  completed
ECSA , F5  Run  13 F5  completed
ECSA , F5  Run  14 F5  completed
ECSA , F5  Run  15 F5  completed
ECSA , F5  Run  16 F5  completed
ECSA , F5  Run  17 F5  completed
ECSA , F5  Run  18 F5  completed
ECSA , F5  Run  19 F5  completed
ECSA , F5  Run  20 F5  completed
ECSA , F5  Run  21 F5  completed
ECSA , F5  Run  22 F5  completed
ECSA , F5  Run  23 F5  completed
ECSA , F5  Run  24 F

ECSA , F13  Run  0 F13  completed
ECSA , F13  Run  1 F13  completed
ECSA , F13  Run  2 F13  completed
ECSA , F13  Run  3 F13  completed
ECSA , F13  Run  4 F13  completed
ECSA , F13  Run  5 F13  completed
ECSA , F13  Run  6 F13  completed
ECSA , F13  Run  7 F13  completed
ECSA , F13  Run  8 F13  completed
ECSA , F13  Run  9 F13  completed
ECSA , F13  Run  10 F13  completed
ECSA , F13  Run  11 F13  completed
ECSA , F13  Run  12 F13  completed
ECSA , F13  Run  13 F13  completed
ECSA , F13  Run  14 F13  completed
ECSA , F13  Run  15 F13  completed
ECSA , F13  Run  16 F13  completed
ECSA , F13  Run  17 F13  completed
ECSA , F13  Run  18 F13  completed
ECSA , F13  Run  19 F13  completed
ECSA , F13  Run  20 F13  completed
ECSA , F13  Run  21 F13  completed
ECSA , F13  Run  22 F13  completed
ECSA , F13  Run  23 F13  completed
ECSA , F13  Run  24 F13  completed
ECSA , F13  Run  25 F13  completed
ECSA , F13  Run  26 F13  completed
ECSA , F13  Run  27 F13  completed
ECSA , F13  Run  28 F13  compl

ECSA , F20  Run  27 F20  completed
ECSA , F20  Run  28 F20  completed
ECSA , F20  Run  29 F20  completed
ECSA , F21  Run  0 F21  completed
ECSA , F21  Run  1 F21  completed
ECSA , F21  Run  2 F21  completed
ECSA , F21  Run  3 F21  completed
ECSA , F21  Run  4 F21  completed
ECSA , F21  Run  5 F21  completed
ECSA , F21  Run  6 F21  completed
ECSA , F21  Run  7 F21  completed
ECSA , F21  Run  8 F21  completed
ECSA , F21  Run  9 F21  completed
ECSA , F21  Run  10 F21  completed
ECSA , F21  Run  11 F21  completed
ECSA , F21  Run  12 F21  completed
ECSA , F21  Run  13 F21  completed
ECSA , F21  Run  14 F21  completed
ECSA , F21  Run  15 F21  completed
ECSA , F21  Run  16 F21  completed
ECSA , F21  Run  17 F21  completed
ECSA , F21  Run  18 F21  completed
ECSA , F21  Run  19 F21  completed
ECSA , F21  Run  20 F21  completed
ECSA , F21  Run  21 F21  completed
ECSA , F21  Run  22 F21  completed
ECSA , F21  Run  23 F21  completed
ECSA , F21  Run  24 F21  completed
ECSA , F21  Run  25 F21  compl

In [2]:
gen = 10
for t in range (0,gen):
    E1 = 0.05 + (t / gen)
    print(E1)

0.05
0.15000000000000002
0.25
0.35
0.45
0.55
0.65
0.75
0.8500000000000001
0.9500000000000001
ERROR! Session/line number was not unique in database. History logging moved to new session 1342


In [5]:
gen = 10
for t in range (0,gen):
    E1 = 2*(1- (t / gen))
    print(E1)

2.0
1.8
1.6
1.4
1.2
1.0
0.8
0.6000000000000001
0.3999999999999999
0.19999999999999996


In [14]:
import numpy
import math

def Ufun(x, a, k, m):
    y = k * ((x - a) ** m) * (x > a) + k * ((-x - a) ** m) * (x < (-a))
    return y

x = numpy.array([-50,-30,0 ,10 ,15 ,45 ,50])
#x = numpy.array([-50,-1,0 ,10 ,15.6 ,45 ,50])
#x = numpy.array([-15,-1,0 ,6 ,15.6 ,45 ,44])

dim = len(x)
print(dim)
o = 0.1 * (
        (numpy.sin(3 * numpy.pi * x[0])) ** 2
        + numpy.sum(
            (x[: dim - 1] - 1) ** 2
            * (1 + (numpy.sin(3 * numpy.pi * x[1 :])) ** 2)
        )
        + ((x[dim-1] - 1) ** 2) * (1 + (numpy.sin(2 * numpy.pi * x[dim-1])) ** 2)
    ) + numpy.sum(Ufun(x, 5, 100, 4))
o = "{:.4e}".format(o)
print(o)

7
1.1163e+09


In [26]:
for t in range (0,1000):
    AP = 0.05 * pow(2 , t/1000)
    #fl = 2.0 * pow(0.15, math.sqrt(t)/1000)
    print(AP)

0.05
0.05003466937312904
0.05006936278556673
0.050104080253981644
0.05013882179505389
0.05017358742547515
0.05020837716194866
0.05024319102118927
0.05027802901992341
0.05031289117488909
0.05034777750283595
0.0503826880205252
0.05041762274472975
0.05045258169223407
0.050487564879834294
0.05052257232433819
0.05055760404256521
0.05059266005134644
0.05062774036752465
0.050662845007954274
0.05069797398950146
0.05073312732904402
0.05076830504347149
0.050803507149685095
0.05083873366459782
0.050873984605134315
0.05090925998823104
0.050944559830836136
0.05097988414990953
0.051015232962422885
0.05105060628535967
0.05108600413571507
0.05112142653049612
0.0511568734867216
0.051192345021422114
0.05122784115164008
0.0512633618944297
0.05129890726685702
0.05133447728599995
0.051370071968948196
0.05140569133280333
0.05144133539467878
0.05147700417169986
0.05151269768100373
0.05154841593973944
0.051584158965067954
0.0516199267741621
0.05165571938420663
0.05169153681239822
0.05172737907594546
0.0517632

In [2]:
import numpy
numpy.random.randn(5)

array([ 0.00267224,  0.47315145,  0.53669826, -0.55219737,  0.86303345])

In [41]:
import random
K_max = 20
K_min = 1
for t in range (0,500):
    K = round(K_min + t * ((K_max - K_min)/500))
    #fl = 2.0 * pow(0.15, math.sqrt(t)/1000)
    print(K)
    
    #Return a k length list of unique elements chosen from the population sequence. Used for random sampling without replacement.
    tour = random.sample(range(0, 30), K)
    print(tour)

1


ValueError: list.remove(x): x not in list

In [35]:
random.sample(range(0, 3), 3)

[1, 0, 2]

In [54]:
K = 1
fitness = [100.5, 50.5, 30, 29.3, 15, 32, 12]
tour = [4]
#print(len(tour))
best = -1
for i in range (0, K):
    ind = tour[i]
    print(ind)
    if (best == -1 or fitness[ind] < fitness[best]):
        best = ind
print (best)
print (fitness[best])

4
4
15


In [26]:
import numpy
K=3
fitness = [100.5, 50.5, 30, 29.3, 15, 32, 12]
I = numpy.argsort(fitness)
print(I)
Best_K = I[0:K]
print(Best_K)

#num = numpy.random.choice(Best_K,2, replace=False)
num = numpy.random.choice(Best_K,1)

print(num)


[6 4 3 2 5 1 0]
[6 4 3]
[4]


In [9]:
import numpy
xn = numpy.array([[1, 1, 1], [0, 0, 0], [1, 1, 0], [1, 0, 0], [0, 1, 0],[1, 0, 1]])
print(xn)
dim = 3
PopSize = 6
diversity_list = []
centroid = numpy.zeros(dim)
I = 0
for i in range (0,dim):
    for j in range(0,PopSize):
        centroid[i] += xn[j,i] / PopSize

print("centroid", centroid)           
for i in range (0, dim):
    for j in range (0, PopSize):
        I += (xn[j,i] - centroid[i])**2
diversity_list.append(float(I))
print("diversity = ", diversity_list)

[[1 1 1]
 [0 0 0]
 [1 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 1]]
centroid [0.66666667 0.5        0.33333333]
diversity =  [4.166666666666667]


In [10]:
import numpy
xn = numpy.array([[1, 1, 1], [0, 0, 0], [1, 1, 0], [1, 0, 0], [0, 1, 0],[1, 0, 1]])
print(xn)
dim = 3
PopSize = 6
diversity_list = []
centroid = numpy.zeros(dim)
I = 0
for i in range (0,dim):
    for j in range(0,PopSize):
        centroid[i] += xn[j,i] / PopSize

print("centroid", centroid)           
for i in range (0, dim):
    for j in range (0, PopSize):
        I += (xn[j,i] - centroid[i])**2
diversity_list.append(float(I))
print("diversity = ", diversity_list)

[[1 1 1]
 [0 0 0]
 [1 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 1]]
centroid [0.66666667 0.5        0.33333333]
diversity =  [4.166666666666667]


In [2]:
#Verify moment_of_inertia function in diversity_measures module

import My_Algorithms.diversity_measures as dv
import numpy
xn = numpy.array([[1, 1, 1], [0, 0, 0], [1, 1, 0], [1, 0, 0], [0, 1, 0],[1, 0, 1]])
dim = 3
PopSize = 6
I = dv.moment_of_inertia(xn, dim, PopSize)
print("diversity = ", I*PopSize)




diversity =  25.0


In [3]:
import sys
print (sys.modules["My_Algorithms"])

KeyError: 'My_Algorithms'

In [2]:
import numpy as geek
 
# input array
in_arr = geek.array([2, 0, 1, 5, 4, 1, 9])
print("Input unsorted array : ", in_arr)
 
out_arr = geek.argsort(in_arr)
print("Output sorted array indices : ", out_arr)
print("Output sorted array : ", in_arr[out_arr])

Input unsorted array :  [2 0 1 5 4 1 9]
Output sorted array indices :  [1 2 5 0 4 3 6]
Output sorted array :  [0 1 1 2 4 5 9]
ERROR! Session/line number was not unique in database. History logging moved to new session 1375
